name: Deploy Backend to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Dependencies
        run: |
          cd api/calculateRisk
          npm install
          
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "health-insurance-riskcalculator-api"
          package: api/calculateRisk

      - name: Logout from Azure
        run: az logout
