name: Build and deploy Node.js project to Azure Function App - health-insurance-riskcalculator-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Resolve Project Dependencies Using Npm
        shell: pwsh
        run: |
          cd api/calculateRisk
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: ./api/calculateRisk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-functionapp.outputs.app-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: ./api/calculateRisk

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "health-insurance-riskcalculator-api"
          package: './api/calculateRisk'

      - name: Logout from Azure
        run: az
